[package]
name = "kubesend"
version = "0.1.0"
edition = "2021"

[dependencies]
mail-send = "0.5.1"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
serde_yaml = "0.9"