apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "kubesend.fullname" .) }}
spec:
  selector:
    app: kubesend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: 8080
