# Service configuration
service:
  name: kubesend
  type: ClusterIP
  port: 80

# Resource constraints
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Application configuration
config:
  smtp:
    host: "smtp.example.com"
    port: 465
    username: "kubesend@example.com"
    password: "abc123"
    useTls: true
  general:
    logLevel: "info"
    notificationRetries: 3
