apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesend.name" . }}-config
data:
  config.yaml: |
    smtp:
      host: {{ .Values.config.smtp.host | default "smtp.example.com" | quote }}
      port: {{ .Values.config.smtp.port | default 465 }}
      username: {{ .Values.config.smtp.username | default "kubesend@example.com" | quote }}
      password: {{ .Values.config.smtp.password | default "abc123" | quote }}
      use_tls: {{ .Values.config.smtp.useTls | default true }}

    general:
      log_level: {{ .Values.config.general.logLevel | default "info" | quote }}
      notification_retries: {{ .Values.config.general.notificationRetries | default 3 }}