apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesend.name" . }}-deployment
  labels:
    app: kubesend
spec:
  replicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  selector:
    matchLabels:
      app: kubesend
  strategy:
    type: RollingUpdate  
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  template:
    metadata:
      labels:
        app: kubesend
    spec:
      containers:
        - name: kubesend
          image: "v3xl/kubesend:{{ default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - -L
                - http://localhost:8080/          
            initialDelaySeconds: 5
            periodSeconds: 5                  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "50m" }}
              memory: {{ .Values.resources.requests.memory | default "32Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "100m" }}
              memory: {{ .Values.resources.limits.memory | default "128Mi" }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config/config.yaml
            subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "kubesend.name" . }}-config
