apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesend.name" . }}-service
spec:
  selector:
    app: {{ include "kubesend.name" . }}-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: 8080
