apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesend.fullname" . }}
  labels:
    app: {{ include "kubesend.name" . }}
spec:
  # Simple replicas configuration
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubesend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubesend.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # Basic resource requests and limits
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}
