name: Docker Image CI

on:
  push:
    branches: [ "main" ] #Initial testing only
  pull_request:
    branches: [ "main" ] #Initial testing only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Get current version #Get current version from the Cargo.toml file
        id: version
        run: |
          VERSION=$(grep -m1 '^version = ' Cargo.toml | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/kubesend:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/kubesend:latest